[package]
name = "sea"
version = "0.0.1-dev"
edition = "2021"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
strum = { version = "0.27.1", features = ["derive"] }
text_io = "0.1.13"
thiserror = "2.0.12"
